### ISSUE TITLE
异域花园-无法正常合成

### ISSUE THREAD

**Issue by shuiPingPing** [haiman233/Slimefun4_Integration_package#1]
![5e7cb742b9484a41373bc8524ec95d4](https://github.com/user-attachments/assets/19c958c8-ad59-4905-8f44-ea519b452f8c)
![6074dcdd72b546cd62dc251536e5bb7](https://github.com/user-attachments/assets/8afc13f6-e40c-47ee-8ad4-a8d8af75f368)
![a725d9d2ffc0f298da82a8c86366b2c](https://github.com/user-attachments/assets/a6198c53-0de1-4a8c-a9ca-692b6ef65843)
![b5e1db1d2e09d6a4e119f732e9d8985](https://github.com/user-attachments/assets/4f62f344-7f32-4d2e-91e6-9f854cad4416)

以上为游戏内截图，在异域花园厨房内按粘液科技书里配方指示放置后，无法正常合成
以下为服务器日志文件
[latest.log](https://github.com/user-attachments/files/17088288/latest.log)

客户端为：https://github.com/haiman233/Slimefun4_JEI_All_Addon

希望能得到解决

QQ : 809287578

**Comment by haiman233** [comment]
知道问题了，是林业蜜蜂的多方块机器与厨房冲突了（都包含发射器与活板门）
你可以在粘液书里搜索一下快捷多方块结构模拟器，使用这个机器去完成厨房配方的制作

**Comment by shuiPingPing** [comment]
好的

**Comment by shuiPingPing** [comment]
但是这个多方块结构模拟器正常游玩得很后期才能合成，不过倒是不怎么影响游玩，毕竟模组多，哈哈

**Comment by haiman233** [comment]
我在v3版本修一下

**Comment by shuiPingPing** [comment]
ok
